// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../../encoding/json/models.js";

export class Download {
    /**
     * Creates a new Download instance.
     * @param {Partial<Download>} [$$source = {}] - The source object to create the Download.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Url"] = "";
        }
        if (!("Options" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["Options"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Download instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Download}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Options" in $$parsedSource) {
            $$parsedSource["Options"] = $$createField2_0($$parsedSource["Options"]);
        }
        return new Download(/** @type {Partial<Download>} */($$parsedSource));
    }
}

export class Thumbnail {
    /**
     * Creates a new Thumbnail instance.
     * @param {Partial<Thumbnail>} [$$source = {}] - The source object to create the Thumbnail.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {json$0.Number}
             */
            this["height"] = "";
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {json$0.Number}
             */
            this["width"] = "";
        }
        if (!("resolution" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resolution"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Thumbnail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Thumbnail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Thumbnail(/** @type {Partial<Thumbnail>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
