// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../../encoding/json/models.js";

export class Download {
    "ID": string;
    "Url": string;
    "Options": string[];

    /** Creates a new Download instance. */
    constructor($$source: Partial<Download> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Url" in $$source)) {
            this["Url"] = "";
        }
        if (!("Options" in $$source)) {
            this["Options"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Download instance from a string or object.
     */
    static createFrom($$source: any = {}): Download {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Options" in $$parsedSource) {
            $$parsedSource["Options"] = $$createField2_0($$parsedSource["Options"]);
        }
        return new Download($$parsedSource as Partial<Download>);
    }
}

export class Thumbnail {
    "url": string;
    "height": json$0.Number;
    "width": json$0.Number;
    "resolution": string;

    /** Creates a new Thumbnail instance. */
    constructor($$source: Partial<Thumbnail> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("height" in $$source)) {
            this["height"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = "";
        }
        if (!("resolution" in $$source)) {
            this["resolution"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Thumbnail instance from a string or object.
     */
    static createFrom($$source: any = {}): Thumbnail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Thumbnail($$parsedSource as Partial<Thumbnail>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
