// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ytdlp$0 from "../exec/ytdlp/models.js";

export class DownloadProgress {
    "ID": string;
    "Data": ytdlp$0.ProgressFormat;

    /** Creates a new DownloadProgress instance. */
    constructor($$source: Partial<DownloadProgress> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Data" in $$source)) {
            this["Data"] = (new ytdlp$0.ProgressFormat());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadProgress {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Data" in $$parsedSource) {
            $$parsedSource["Data"] = $$createField1_0($$parsedSource["Data"]);
        }
        return new DownloadProgress($$parsedSource as Partial<DownloadProgress>);
    }
}

// Private type creation functions
const $$createType0 = ytdlp$0.ProgressFormat.createFrom;
