// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * NullTime represents a [time.Time] that may be null.
 * NullTime implements the [Scanner] interface so
 * it can be used as a scan destination, similar to [NullString].
 */
export class NullTime {
    "Time": time$0.Time;

    /**
     * Valid is true if Time is not NULL
     */
    "Valid": boolean;

    /** Creates a new NullTime instance. */
    constructor($$source: Partial<NullTime> = {}) {
        if (!("Time" in $$source)) {
            this["Time"] = null;
        }
        if (!("Valid" in $$source)) {
            this["Valid"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NullTime instance from a string or object.
     */
    static createFrom($$source: any = {}): NullTime {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NullTime($$parsedSource as Partial<NullTime>);
    }
}
