// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ytdlp} from '../models';
import {context} from '../models';

export function AddToQueue(arg1:ytdlp.Download):Promise<string>;

export function GetHighDefinitionThumbnail(arg1:string):Promise<string>;

export function GetThumbnails(arg1:string):Promise<Array<ytdlp.Thumbnail>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartQueue():Promise<void>;

export function StopQueue():Promise<void>;
