// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHighDefinitionThumbnail(arg1:string):Promise<string>;

export function GetThumbnails(arg1:string):Promise<string>;
