// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToQueue(arg1) {
  return window['go']['ytdlp']['YtDlp']['AddToQueue'](arg1);
}

export function GetHighDefinitionThumbnail(arg1) {
  return window['go']['ytdlp']['YtDlp']['GetHighDefinitionThumbnail'](arg1);
}

export function GetThumbnails(arg1) {
  return window['go']['ytdlp']['YtDlp']['GetThumbnails'](arg1);
}

export function StartQueue(arg1, arg2) {
  return window['go']['ytdlp']['YtDlp']['StartQueue'](arg1, arg2);
}

export function StopQueue() {
  return window['go']['ytdlp']['YtDlp']['StopQueue']();
}
