// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ytdlp} from '../models';

export function GetHighDefinitionThumbnail(arg1:string):Promise<string>;

export function GetThumbnails(arg1:string):Promise<ytdlp.ThumbnailJson>;
