// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../../../db/models.js";

export function AddToQueue(trackId: number): $CancellablePromise<void> {
    return $Call.ByID(510539471, trackId);
}

export function GetPlaylistTracks(playlistId: number): $CancellablePromise<db$0.Track[]> {
    return $Call.ByID(3124403020, playlistId).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = db$0.Track.createFrom;
const $$createType1 = $Create.Array($$createType0);
