// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../db/models/models.js";

export function GetAlbumTracks(albumId: number): $CancellablePromise<models$0.Track[]> {
    return $Call.ByID(1171505149, albumId).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetPlaylistTracks(playlistId: number): $CancellablePromise<models$0.Track[]> {
    return $Call.ByID(3124403020, playlistId).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Play(trackId: number, vol: number): $CancellablePromise<void> {
    return $Call.ByID(3491172388, trackId, vol);
}

// Private type creation functions
const $$createType0 = models$0.Track.createFrom;
const $$createType1 = $Create.Array($$createType0);
