// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../db/models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateDownload(download: models$0.Download | null): $CancellablePromise<void> {
    return $Call.ByID(1054166972, download);
}

export function GetAlbumTracks(albumId: number): $CancellablePromise<models$0.Track[]> {
    return $Call.ByID(2008145467, albumId).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetAlbums(): $CancellablePromise<$models.AlbumWithoutTracks[]> {
    return $Call.ByID(2558610760).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetDownload(id: string): $CancellablePromise<models$0.Download> {
    return $Call.ByID(238834004, id).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetPlaylist(playlistId: number): $CancellablePromise<models$0.Playlist> {
    return $Call.ByID(2359039234, playlistId).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetPlaylists(): $CancellablePromise<$models.PlaylistWithoutTracks[]> {
    return $Call.ByID(3400909027).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetTrack(trackId: number): $CancellablePromise<models$0.Track> {
    return $Call.ByID(525570019, trackId).then(($result: any) => {
        return $$createType0($result);
    });
}

export function PendingDownloads(): $CancellablePromise<models$0.Download[]> {
    return $Call.ByID(372641140).then(($result: any) => {
        return $$createType8($result);
    });
}

export function SetDownloadFinishedAt(downloadId: string, finishedAt: time$0.Time): $CancellablePromise<void> {
    return $Call.ByID(1515963227, downloadId, finishedAt);
}

export function UpdateDownloadFinishedAt(id: string, value: time$0.Time): $CancellablePromise<void> {
    return $Call.ByID(3620325518, id, value);
}

// Private type creation functions
const $$createType0 = models$0.Track.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.AlbumWithoutTracks.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = models$0.Download.createFrom;
const $$createType5 = models$0.Playlist.createFrom;
const $$createType6 = $models.PlaylistWithoutTracks.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($$createType4);
