// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ytdlp$0 from "../exec/ytdlp/models.js";

/**
 * @param {string} url
 * @param {string[]} opts
 * @returns {$CancellablePromise<string>}
 */
export function EnqueueDownload(url, ...opts) {
    return $Call.ByID(4241619596, url, opts);
}

/**
 * @returns {$CancellablePromise<ytdlp$0.Download[]>}
 */
export function PendingDownloads() {
    return $Call.ByID(774058486).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = ytdlp$0.Download.createFrom;
const $$createType1 = $Create.Array($$createType0);
