// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../db/models/models.js";

export class AlbumWithoutTracks {
    "ID": number;
    "Title": string;
    "Artists": (models$0.Artist | null)[];

    /** Creates a new AlbumWithoutTracks instance. */
    constructor($$source: Partial<AlbumWithoutTracks> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Artists" in $$source)) {
            this["Artists"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlbumWithoutTracks instance from a string or object.
     */
    static createFrom($$source: any = {}): AlbumWithoutTracks {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Artists" in $$parsedSource) {
            $$parsedSource["Artists"] = $$createField2_0($$parsedSource["Artists"]);
        }
        return new AlbumWithoutTracks($$parsedSource as Partial<AlbumWithoutTracks>);
    }
}

export class PlaylistWithoutTracks {
    "ID": number;
    "Title": string;

    /** Creates a new PlaylistWithoutTracks instance. */
    constructor($$source: Partial<PlaylistWithoutTracks> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaylistWithoutTracks instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaylistWithoutTracks {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaylistWithoutTracks($$parsedSource as Partial<PlaylistWithoutTracks>);
    }
}

// Private type creation functions
const $$createType0 = models$0.Artist.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
