// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ytdlp$0 from "../exec/ytdlp/models.js";

export function GetHighDefinitionThumbnail(url: string): $CancellablePromise<string> {
    return $Call.ByID(1337970040, url);
}

export function GetThumbnails(url: string): $CancellablePromise<ytdlp$0.Thumbnail[]> {
    return $Call.ByID(1917803800, url).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = ytdlp$0.Thumbnail.createFrom;
const $$createType1 = $Create.Array($$createType0);
