// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ytdlp$0 from "../exec/ytdlp/models.js";

/**
 * @param {string} url
 * @returns {$CancellablePromise<string>}
 */
export function GetHighDefinitionThumbnail(url) {
    return $Call.ByID(1337970040, url);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<ytdlp$0.Thumbnail[]>}
 */
export function GetThumbnails(url) {
    return $Call.ByID(1917803800, url).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = ytdlp$0.Thumbnail.createFrom;
const $$createType1 = $Create.Array($$createType0);
