/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: meta.i

package meta

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stddef.h>
#include <stdint.h>


typedef ptrdiff_t intgo;
typedef size_t uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
extern void _wrap_Swig_free_meta_cd840580a47d41c6(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_meta_cd840580a47d41c6(swig_intgo arg1);
extern uintptr_t _wrap_new_TagFile_meta_cd840580a47d41c6(swig_type_1 arg1);
extern void _wrap_TagFile_setAlbum_meta_cd840580a47d41c6(uintptr_t arg1, swig_type_2 arg2);
extern swig_type_3 _wrap_TagFile_getAlbum_meta_cd840580a47d41c6(uintptr_t arg1);
extern void _wrap_delete_TagFile_meta_cd840580a47d41c6(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


func getSwigcptr(v interface { Swigcptr() uintptr }) uintptr {
	if v == nil {
		return 0
	}
	return v.Swigcptr()
}


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string(unsafe.Slice((*byte)(unsafe.Pointer(p.p)), p.n))
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_meta_cd840580a47d41c6(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_meta_cd840580a47d41c6(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrTagFile uintptr

func (p SwigcptrTagFile) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrTagFile) SwigIsTagFile() {
}

func NewTagFile(arg1 string) (_swig_ret TagFile) {
	var swig_r TagFile
	_swig_i_0 := arg1
	swig_r = (TagFile)(SwigcptrTagFile(C._wrap_new_TagFile_meta_cd840580a47d41c6(*(*C.swig_type_1)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func (arg1 SwigcptrTagFile) SetAlbum(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_TagFile_setAlbum_meta_cd840580a47d41c6(C.uintptr_t(_swig_i_0), *(*C.swig_type_2)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrTagFile) GetAlbum() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_TagFile_getAlbum_meta_cd840580a47d41c6(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func DeleteTagFile(arg1 TagFile) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_TagFile_meta_cd840580a47d41c6(C.uintptr_t(_swig_i_0))
}

type TagFile interface {
	Swigcptr() uintptr
	SwigIsTagFile()
	SetAlbum(arg2 string)
	GetAlbum() (_swig_ret string)
}


