/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: meta.i


extern
#ifdef __cplusplus
  "C"
#endif
  void cgo_panic__meta_8f12316039e5a9d9(const char*);
static void _swig_gopanic(const char *p) {
  cgo_panic__meta_8f12316039e5a9d9(p);
}



#define SWIG_VERSION 0x040401
#define SWIGGO
#define SWIGMODULE meta
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NOEXCEPT noexcept
#else
# define SWIG_NOEXCEPT throw()
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 *
 * Note that SWIG expects __cplusplus to be defined to the appropriate C++ standard.
 * MSVC users are urged to check and examine the /Zc:__cplusplus compiler option.
 * See https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef ptrdiff_t intgo;
typedef size_t uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



#define SWIG_exception(code, msg) _swig_gopanic(msg)


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif

#if defined(__cplusplus) && (__cplusplus >=201103L)
# define SWIG_OVERRIDE override
#else
# define SWIG_OVERRIDE
#endif



static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include <vector>
#include <stdexcept>


#include <string>


#include <typeinfo>
#include <stdexcept>


#include <utility>

SWIGINTERN std::vector< std::string >::const_reference std_vector_Sl_std_string_Sg__get(std::vector< std::string > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_std_string_Sg__set(std::vector< std::string > *self,int i,std::vector< std::string >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN std::vector< char >::const_reference std_vector_Sl_char_Sg__get(std::vector< char > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_char_Sg__set(std::vector< char > *self,int i,std::vector< char >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }

#include "tagfile.hpp"

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_meta_8f12316039e5a9d9(void *_swig_go_0) {
  void *arg1 = 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_meta_8f12316039e5a9d9(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


std::vector< std::string > *_wrap_new_StringVector__SWIG_0_meta_8f12316039e5a9d9() {
  std::vector< std::string > *result = 0 ;
  std::vector< std::string > *_swig_go_result;
  
  
  result = (std::vector< std::string > *)new std::vector< std::string >();
  *(std::vector< std::string > **)&_swig_go_result = (std::vector< std::string > *)result; 
  return _swig_go_result;
}


std::vector< std::string > *_wrap_new_StringVector__SWIG_1_meta_8f12316039e5a9d9(long long _swig_go_0) {
  std::vector< std::string >::size_type arg1 ;
  std::vector< std::string > *result = 0 ;
  std::vector< std::string > *_swig_go_result;
  
  arg1 = (size_t)_swig_go_0; 
  
  result = (std::vector< std::string > *)new std::vector< std::string >(SWIG_STD_MOVE(arg1));
  *(std::vector< std::string > **)&_swig_go_result = (std::vector< std::string > *)result; 
  return _swig_go_result;
}


std::vector< std::string > *_wrap_new_StringVector__SWIG_2_meta_8f12316039e5a9d9(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = 0 ;
  std::vector< std::string > *result = 0 ;
  std::vector< std::string > *_swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  result = (std::vector< std::string > *)new std::vector< std::string >((std::vector< std::string > const &)*arg1);
  *(std::vector< std::string > **)&_swig_go_result = (std::vector< std::string > *)result; 
  return _swig_go_result;
}


long long _wrap_StringVector_size_meta_8f12316039e5a9d9(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = 0 ;
  std::vector< std::string >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  result = ((std::vector< std::string > const *)arg1)->size();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_StringVector_capacity_meta_8f12316039e5a9d9(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = 0 ;
  std::vector< std::string >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  result = ((std::vector< std::string > const *)arg1)->capacity();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_StringVector_reserve_meta_8f12316039e5a9d9(std::vector< std::string > *_swig_go_0, long long _swig_go_1) {
  std::vector< std::string > *arg1 = 0 ;
  std::vector< std::string >::size_type arg2 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  (arg1)->reserve(SWIG_STD_MOVE(arg2));
  
}


bool _wrap_StringVector_isEmpty_meta_8f12316039e5a9d9(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  result = (bool)((std::vector< std::string > const *)arg1)->empty();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_StringVector_clear_meta_8f12316039e5a9d9(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = 0 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  (arg1)->clear();
  
}


void _wrap_StringVector_add_meta_8f12316039e5a9d9(std::vector< std::string > *_swig_go_0, _gostring_ _swig_go_1) {
  std::vector< std::string > *arg1 = 0 ;
  std::vector< std::string >::value_type *arg2 = 0 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  std::vector< std::string >::value_type arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  (arg1)->push_back((std::vector< std::string >::value_type const &)*arg2);
  
}


_gostring_ _wrap_StringVector_get_meta_8f12316039e5a9d9(std::vector< std::string > *_swig_go_0, intgo _swig_go_1) {
  std::vector< std::string > *arg1 = 0 ;
  int arg2 ;
  std::vector< std::string >::value_type *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  try {
    result = (std::vector< std::string >::value_type *) &std_vector_Sl_std_string_Sg__get(arg1,arg2);
  } catch(std::out_of_range &_e) {
    _swig_gopanic((&_e)->what());
  }
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_StringVector_set_meta_8f12316039e5a9d9(std::vector< std::string > *_swig_go_0, intgo _swig_go_1, _gostring_ _swig_go_2) {
  std::vector< std::string > *arg1 = 0 ;
  int arg2 ;
  std::vector< std::string >::value_type *arg3 = 0 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  std::vector< std::string >::value_type arg3_str(_swig_go_2.p, _swig_go_2.n);
  arg3 = &arg3_str;
  
  
  try {
    std_vector_Sl_std_string_Sg__set(arg1,arg2,(std::string const &)*arg3);
  } catch(std::out_of_range &_e) {
    _swig_gopanic((&_e)->what());
  }
  
}


void _wrap_delete_StringVector_meta_8f12316039e5a9d9(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = 0 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  delete arg1;
  
}


std::vector< char > *_wrap_new_ByteVector__SWIG_0_meta_8f12316039e5a9d9() {
  std::vector< char > *result = 0 ;
  std::vector< char > *_swig_go_result;
  
  
  result = (std::vector< char > *)new std::vector< char >();
  *(std::vector< char > **)&_swig_go_result = (std::vector< char > *)result; 
  return _swig_go_result;
}


std::vector< char > *_wrap_new_ByteVector__SWIG_1_meta_8f12316039e5a9d9(long long _swig_go_0) {
  std::vector< char >::size_type arg1 ;
  std::vector< char > *result = 0 ;
  std::vector< char > *_swig_go_result;
  
  arg1 = (size_t)_swig_go_0; 
  
  result = (std::vector< char > *)new std::vector< char >(SWIG_STD_MOVE(arg1));
  *(std::vector< char > **)&_swig_go_result = (std::vector< char > *)result; 
  return _swig_go_result;
}


std::vector< char > *_wrap_new_ByteVector__SWIG_2_meta_8f12316039e5a9d9(std::vector< char > *_swig_go_0) {
  std::vector< char > *arg1 = 0 ;
  std::vector< char > *result = 0 ;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  
  result = (std::vector< char > *)new std::vector< char >((std::vector< char > const &)*arg1);
  *(std::vector< char > **)&_swig_go_result = (std::vector< char > *)result; 
  return _swig_go_result;
}


long long _wrap_ByteVector_size_meta_8f12316039e5a9d9(std::vector< char > *_swig_go_0) {
  std::vector< char > *arg1 = 0 ;
  std::vector< char >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  
  result = ((std::vector< char > const *)arg1)->size();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_ByteVector_capacity_meta_8f12316039e5a9d9(std::vector< char > *_swig_go_0) {
  std::vector< char > *arg1 = 0 ;
  std::vector< char >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  
  result = ((std::vector< char > const *)arg1)->capacity();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_ByteVector_reserve_meta_8f12316039e5a9d9(std::vector< char > *_swig_go_0, long long _swig_go_1) {
  std::vector< char > *arg1 = 0 ;
  std::vector< char >::size_type arg2 ;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  (arg1)->reserve(SWIG_STD_MOVE(arg2));
  
}


bool _wrap_ByteVector_isEmpty_meta_8f12316039e5a9d9(std::vector< char > *_swig_go_0) {
  std::vector< char > *arg1 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  
  result = (bool)((std::vector< char > const *)arg1)->empty();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_ByteVector_clear_meta_8f12316039e5a9d9(std::vector< char > *_swig_go_0) {
  std::vector< char > *arg1 = 0 ;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  
  (arg1)->clear();
  
}


void _wrap_ByteVector_add_meta_8f12316039e5a9d9(std::vector< char > *_swig_go_0, char _swig_go_1) {
  std::vector< char > *arg1 = 0 ;
  std::vector< char >::value_type *arg2 = 0 ;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  arg2 = (std::vector< char >::value_type *)&_swig_go_1; 
  
  (arg1)->push_back((std::vector< char >::value_type const &)*arg2);
  
}


char _wrap_ByteVector_get_meta_8f12316039e5a9d9(std::vector< char > *_swig_go_0, intgo _swig_go_1) {
  std::vector< char > *arg1 = 0 ;
  int arg2 ;
  std::vector< char >::value_type *result = 0 ;
  char _swig_go_result;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  try {
    result = (std::vector< char >::value_type *) &std_vector_Sl_char_Sg__get(arg1,arg2);
  } catch(std::out_of_range &_e) {
    _swig_gopanic((&_e)->what());
  }
  _swig_go_result = (char)*result; 
  return _swig_go_result;
}


void _wrap_ByteVector_set_meta_8f12316039e5a9d9(std::vector< char > *_swig_go_0, intgo _swig_go_1, char _swig_go_2) {
  std::vector< char > *arg1 = 0 ;
  int arg2 ;
  std::vector< char >::value_type *arg3 = 0 ;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (std::vector< char >::value_type *)&_swig_go_2; 
  
  try {
    std_vector_Sl_char_Sg__set(arg1,arg2,(char const &)*arg3);
  } catch(std::out_of_range &_e) {
    _swig_gopanic((&_e)->what());
  }
  
}


void _wrap_delete_ByteVector_meta_8f12316039e5a9d9(std::vector< char > *_swig_go_0) {
  std::vector< char > *arg1 = 0 ;
  
  arg1 = *(std::vector< char > **)&_swig_go_0; 
  
  delete arg1;
  
}


std::pair< std::vector< char >,std::string > *_wrap_new_ByteStringPair__SWIG_0_meta_8f12316039e5a9d9() {
  std::pair< std::vector< char >,std::string > *result = 0 ;
  std::pair< std::vector< char >,std::string > *_swig_go_result;
  
  
  result = (std::pair< std::vector< char >,std::string > *)new std::pair< std::vector< char >,std::string >();
  *(std::pair< std::vector< char >,std::string > **)&_swig_go_result = (std::pair< std::vector< char >,std::string > *)result; 
  return _swig_go_result;
}


std::pair< std::vector< char >,std::string > *_wrap_new_ByteStringPair__SWIG_1_meta_8f12316039e5a9d9(std::vector< char > *_swig_go_0, _gostring_ _swig_go_1) {
  std::vector< char > arg1 ;
  std::string arg2 ;
  std::vector< char > *argp1 ;
  std::pair< std::vector< char >,std::string > *result = 0 ;
  std::pair< std::vector< char >,std::string > *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  (&arg2)->assign(_swig_go_1.p, _swig_go_1.n); 
  
  result = (std::pair< std::vector< char >,std::string > *)new std::pair< std::vector< char >,std::string >(SWIG_STD_MOVE(arg1),SWIG_STD_MOVE(arg2));
  *(std::pair< std::vector< char >,std::string > **)&_swig_go_result = (std::pair< std::vector< char >,std::string > *)result; 
  return _swig_go_result;
}


std::pair< std::vector< char >,std::string > *_wrap_new_ByteStringPair__SWIG_2_meta_8f12316039e5a9d9(std::pair< std::vector< char >,std::string > *_swig_go_0) {
  std::pair< std::vector< char >,std::string > *arg1 = 0 ;
  std::pair< std::vector< char >,std::string > *result = 0 ;
  std::pair< std::vector< char >,std::string > *_swig_go_result;
  
  arg1 = *(std::pair< std::vector< char >,std::string > **)&_swig_go_0; 
  
  result = (std::pair< std::vector< char >,std::string > *)new std::pair< std::vector< char >,std::string >((std::pair< std::vector< char >,std::string > const &)*arg1);
  *(std::pair< std::vector< char >,std::string > **)&_swig_go_result = (std::pair< std::vector< char >,std::string > *)result; 
  return _swig_go_result;
}


void _wrap_ByteStringPair_first_set_meta_8f12316039e5a9d9(std::pair< std::vector< char >,std::string > *_swig_go_0, std::vector< char > *_swig_go_1) {
  std::pair< std::vector< char >,std::string > *arg1 = 0 ;
  std::vector< char > *arg2 = 0 ;
  
  arg1 = *(std::pair< std::vector< char >,std::string > **)&_swig_go_0; 
  arg2 = *(std::vector< char > **)&_swig_go_1; 
  
  if (arg1) (arg1)->first = *arg2;
  
}


std::vector< char > *_wrap_ByteStringPair_first_get_meta_8f12316039e5a9d9(std::pair< std::vector< char >,std::string > *_swig_go_0) {
  std::pair< std::vector< char >,std::string > *arg1 = 0 ;
  std::vector< char > *result = 0 ;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(std::pair< std::vector< char >,std::string > **)&_swig_go_0; 
  
  result = (std::vector< char > *)& ((arg1)->first);
  *(std::vector< char > **)&_swig_go_result = (std::vector< char > *)result; 
  return _swig_go_result;
}


void _wrap_ByteStringPair_second_set_meta_8f12316039e5a9d9(std::pair< std::vector< char >,std::string > *_swig_go_0, _gostring_ _swig_go_1) {
  std::pair< std::vector< char >,std::string > *arg1 = 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = *(std::pair< std::vector< char >,std::string > **)&_swig_go_0; 
  
  std::string arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  if (arg1) (arg1)->second = *arg2;
  
}


_gostring_ _wrap_ByteStringPair_second_get_meta_8f12316039e5a9d9(std::pair< std::vector< char >,std::string > *_swig_go_0) {
  std::pair< std::vector< char >,std::string > *arg1 = 0 ;
  std::string *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(std::pair< std::vector< char >,std::string > **)&_swig_go_0; 
  
  result = (std::string *) & ((arg1)->second);
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_delete_ByteStringPair_meta_8f12316039e5a9d9(std::pair< std::vector< char >,std::string > *_swig_go_0) {
  std::pair< std::vector< char >,std::string > *arg1 = 0 ;
  
  arg1 = *(std::pair< std::vector< char >,std::string > **)&_swig_go_0; 
  
  delete arg1;
  
}


TagFile *_wrap_new_TagFile_meta_8f12316039e5a9d9(_gostring_ _swig_go_0) {
  std::string *arg1 = 0 ;
  TagFile *result = 0 ;
  TagFile *_swig_go_result;
  
  
  std::string arg1_str(_swig_go_0.p, _swig_go_0.n);
  arg1 = &arg1_str;
  
  
  result = (TagFile *)new TagFile((std::string const &)*arg1);
  *(TagFile **)&_swig_go_result = (TagFile *)result; 
  return _swig_go_result;
}


void _wrap_delete_TagFile_meta_8f12316039e5a9d9(TagFile *_swig_go_0) {
  TagFile *arg1 = 0 ;
  
  arg1 = *(TagFile **)&_swig_go_0; 
  
  delete arg1;
  
}


_gostring_ _wrap_TagFile_getTitle_meta_8f12316039e5a9d9(TagFile *_swig_go_0) {
  TagFile *arg1 = 0 ;
  std::string result;
  _gostring_ _swig_go_result;
  
  arg1 = *(TagFile **)&_swig_go_0; 
  
  result = (arg1)->getTitle();
  _swig_go_result = Swig_AllocateString((&result)->data(), (&result)->length()); 
  return _swig_go_result;
}


_gostring_ _wrap_TagFile_getAlbum_meta_8f12316039e5a9d9(TagFile *_swig_go_0) {
  TagFile *arg1 = 0 ;
  std::string result;
  _gostring_ _swig_go_result;
  
  arg1 = *(TagFile **)&_swig_go_0; 
  
  result = (arg1)->getAlbum();
  _swig_go_result = Swig_AllocateString((&result)->data(), (&result)->length()); 
  return _swig_go_result;
}


std::vector< std::string > *_wrap_TagFile_getArtists_meta_8f12316039e5a9d9(TagFile *_swig_go_0) {
  TagFile *arg1 = 0 ;
  std::vector< std::string > *result = 0 ;
  std::vector< std::string > *_swig_go_result;
  
  arg1 = *(TagFile **)&_swig_go_0; 
  
  result = (std::vector< std::string > *) &(arg1)->getArtists();
  *(std::vector< std::string > **)&_swig_go_result = result; 
  return _swig_go_result;
}


std::vector< std::string > *_wrap_TagFile_getAlbumArtists_meta_8f12316039e5a9d9(TagFile *_swig_go_0) {
  TagFile *arg1 = 0 ;
  std::vector< std::string > *result = 0 ;
  std::vector< std::string > *_swig_go_result;
  
  arg1 = *(TagFile **)&_swig_go_0; 
  
  result = (std::vector< std::string > *) &(arg1)->getAlbumArtists();
  *(std::vector< std::string > **)&_swig_go_result = result; 
  return _swig_go_result;
}


std::pair< std::vector< char >,std::string > *_wrap_TagFile_getArtwork_meta_8f12316039e5a9d9(TagFile *_swig_go_0) {
  TagFile *arg1 = 0 ;
  std::pair< std::vector< char >,std::string > result;
  std::pair< std::vector< char >,std::string > *_swig_go_result;
  
  arg1 = *(TagFile **)&_swig_go_0; 
  
  result = (arg1)->getArtwork();
  *(std::pair< std::vector< char >,std::string > **)&_swig_go_result = new std::pair< std::vector< char >,std::string >(result); 
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

