// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Album struct {
	ID      int64
	Title   string
	Artwork []byte
}

type Download struct {
	ID         string
	Options    string
	Url        string
	FinishedAt sql.NullTime
}

type Playlist struct {
	ID    int64
	Title string
}

type PlaylistsTrack struct {
	TrackID    int64
	PlaylistID int64
}

type Track struct {
	ID      int64
	Path    string
	AlbumID int64
}
