// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Download struct {
	ID         string
	Options    string
	Url        string
	FinishedAt sql.NullTime
}
