// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const getDownload = `-- name: GetDownload :one
SELECT id, options, url, finished_at FROM downloads WHERE id = ?
`

func (q *Queries) GetDownload(ctx context.Context, id string) (Download, error) {
	row := q.db.QueryRowContext(ctx, getDownload, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Options,
		&i.Url,
		&i.FinishedAt,
	)
	return i, err
}

const getPendingDownloads = `-- name: GetPendingDownloads :many
SELECT id, options, url, finished_at FROM downloads WHERE finished_at IS NULL
`

func (q *Queries) GetPendingDownloads(ctx context.Context) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, getPendingDownloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Download
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.Options,
			&i.Url,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDownload = `-- name: InsertDownload :exec
INSERT INTO downloads (
  id, url, options, finished_at
  ) VALUES (
  ?, ?, ?, ?
)
`

type InsertDownloadParams struct {
	ID         string
	Url        string
	Options    string
	FinishedAt sql.NullTime
}

func (q *Queries) InsertDownload(ctx context.Context, arg InsertDownloadParams) error {
	_, err := q.db.ExecContext(ctx, insertDownload,
		arg.ID,
		arg.Url,
		arg.Options,
		arg.FinishedAt,
	)
	return err
}

const updateDownloadFinishedAt = `-- name: UpdateDownloadFinishedAt :exec
UPDATE downloads SET finished_at = ? WHERE id = ?
`

type UpdateDownloadFinishedAtParams struct {
	FinishedAt sql.NullTime
	ID         string
}

func (q *Queries) UpdateDownloadFinishedAt(ctx context.Context, arg UpdateDownloadFinishedAtParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadFinishedAt, arg.FinishedAt, arg.ID)
	return err
}
