// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../../../../../gorm.io/gorm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

export class Track {
    "ID": number;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;
    "DeletedAt": gorm$0.DeletedAt;
    "Path": string;

    /** Creates a new Track instance. */
    constructor($$source: Partial<Track> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }
        if (!("DeletedAt" in $$source)) {
            this["DeletedAt"] = null;
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Track instance from a string or object.
     */
    static createFrom($$source: any = {}): Track {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Track($$parsedSource as Partial<Track>);
    }
}
