// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../../../../../database/sql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../../../../../gorm.io/gorm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

export class Album {
    "ID": number;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;
    "DeletedAt": gorm$0.DeletedAt;
    "Title": string;
    "Artists": (Artist | null)[];
    "Tracks": Track[];

    /** Creates a new Album instance. */
    constructor($$source: Partial<Album> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }
        if (!("DeletedAt" in $$source)) {
            this["DeletedAt"] = null;
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Artists" in $$source)) {
            this["Artists"] = [];
        }
        if (!("Tracks" in $$source)) {
            this["Tracks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Album instance from a string or object.
     */
    static createFrom($$source: any = {}): Album {
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Artists" in $$parsedSource) {
            $$parsedSource["Artists"] = $$createField5_0($$parsedSource["Artists"]);
        }
        if ("Tracks" in $$parsedSource) {
            $$parsedSource["Tracks"] = $$createField6_0($$parsedSource["Tracks"]);
        }
        return new Album($$parsedSource as Partial<Album>);
    }
}

export class Artist {
    "ID": number;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;
    "DeletedAt": gorm$0.DeletedAt;
    "Name": string;
    "Albums": (Album | null)[];
    "Tracks": Track[];

    /** Creates a new Artist instance. */
    constructor($$source: Partial<Artist> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }
        if (!("DeletedAt" in $$source)) {
            this["DeletedAt"] = null;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Albums" in $$source)) {
            this["Albums"] = [];
        }
        if (!("Tracks" in $$source)) {
            this["Tracks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Artist instance from a string or object.
     */
    static createFrom($$source: any = {}): Artist {
        const $$createField5_0 = $$createType7;
        const $$createField6_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Albums" in $$parsedSource) {
            $$parsedSource["Albums"] = $$createField5_0($$parsedSource["Albums"]);
        }
        if ("Tracks" in $$parsedSource) {
            $$parsedSource["Tracks"] = $$createField6_0($$parsedSource["Tracks"]);
        }
        return new Artist($$parsedSource as Partial<Artist>);
    }
}

export class Download {
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;
    "DeletedAt": gorm$0.DeletedAt;
    "ID": string;
    "FinishedAt": sql$0.NullTime;
    "Options": string;
    "Source": string;

    /** Creates a new Download instance. */
    constructor($$source: Partial<Download> = {}) {
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }
        if (!("DeletedAt" in $$source)) {
            this["DeletedAt"] = null;
        }
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("FinishedAt" in $$source)) {
            this["FinishedAt"] = (new sql$0.NullTime());
        }
        if (!("Options" in $$source)) {
            this["Options"] = "";
        }
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Download instance from a string or object.
     */
    static createFrom($$source: any = {}): Download {
        const $$createField4_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("FinishedAt" in $$parsedSource) {
            $$parsedSource["FinishedAt"] = $$createField4_0($$parsedSource["FinishedAt"]);
        }
        return new Download($$parsedSource as Partial<Download>);
    }
}

export class Playlist {
    "ID": number;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;
    "DeletedAt": gorm$0.DeletedAt;
    "Title": string;
    "Tracks": Track[];

    /** Creates a new Playlist instance. */
    constructor($$source: Partial<Playlist> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }
        if (!("DeletedAt" in $$source)) {
            this["DeletedAt"] = null;
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Tracks" in $$source)) {
            this["Tracks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Playlist instance from a string or object.
     */
    static createFrom($$source: any = {}): Playlist {
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Tracks" in $$parsedSource) {
            $$parsedSource["Tracks"] = $$createField5_0($$parsedSource["Tracks"]);
        }
        return new Playlist($$parsedSource as Partial<Playlist>);
    }
}

export class Track {
    "ID": number;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;
    "DeletedAt": gorm$0.DeletedAt;
    "Title": string;
    "Artists": (Artist | null)[];
    "Path": string;
    "AlbumID": number;

    /** Creates a new Track instance. */
    constructor($$source: Partial<Track> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }
        if (!("DeletedAt" in $$source)) {
            this["DeletedAt"] = null;
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Artists" in $$source)) {
            this["Artists"] = [];
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("AlbumID" in $$source)) {
            this["AlbumID"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Track instance from a string or object.
     */
    static createFrom($$source: any = {}): Track {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Artists" in $$parsedSource) {
            $$parsedSource["Artists"] = $$createField5_0($$parsedSource["Artists"]);
        }
        return new Track($$parsedSource as Partial<Track>);
    }
}

// Private type creation functions
const $$createType0 = Artist.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = Track.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = Album.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = sql$0.NullTime.createFrom;
