// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Track {
    "ID": number;
    "Path": string;
    "AlbumID": number;

    /** Creates a new Track instance. */
    constructor($$source: Partial<Track> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("AlbumID" in $$source)) {
            this["AlbumID"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Track instance from a string or object.
     */
    static createFrom($$source: any = {}): Track {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Track($$parsedSource as Partial<Track>);
    }
}
