// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToQueue(arg1) {
  return window['go']['main']['App']['AddToQueue'](arg1);
}

export function GetHighDefinitionThumbnail(arg1) {
  return window['go']['main']['App']['GetHighDefinitionThumbnail'](arg1);
}

export function GetThumbnails(arg1) {
  return window['go']['main']['App']['GetThumbnails'](arg1);
}

export function NewAudioFile(arg1) {
  return window['go']['main']['App']['NewAudioFile'](arg1);
}
