// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ytdlp} from '../models';
import {audio} from '../models';

export function AddToDownloadQueue(arg1:ytdlp.Download):Promise<string>;

export function NewAudioFile(arg1:string):Promise<audio.AudioFile>;
