// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {events} from '../models';
import {ytdlp} from '../models';

export function EnqueueDownload(arg1:string,arg2:Array<string>):Promise<string>;

export function EventsEmit(arg1:events.Event,arg2:Array<any>):Promise<void>;

export function GetHighDefinitionThumbnail(arg1:string):Promise<string>;

export function GetThumbnails(arg1:string):Promise<Array<ytdlp.Thumbnail>>;

export function PendingDownloads():Promise<Array<ytdlp.Download>>;
