// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {ytdlp} from '../models';
import {audio} from '../models';

export function AddToQueue(arg1:main.Download):Promise<string>;

export function GetHighDefinitionThumbnail(arg1:string):Promise<string>;

export function GetThumbnails(arg1:string):Promise<Array<ytdlp.Thumbnail>>;

export function NewAudioFile(arg1:string):Promise<audio.AudioFile>;
