// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToDownloadQueue(arg1) {
  return window['go']['main']['App']['AddToDownloadQueue'](arg1);
}

export function NewAudioFile(arg1) {
  return window['go']['main']['App']['NewAudioFile'](arg1);
}
